export const viralHooks = [
  {
    category: 'Sports',
    hooks: [
      'Derek Redmond tore his hamstring mid-race. His dad ran onto the track to help him finish.',
      'Wilma Rudolph overcame polio as a child—and won 3 Olympic golds in one year.',
      'The Leicester City football team had 5,000 to 1 odds to win the Premier League—and did.',
      'Kerri Strug landed a vault on one foot to win Olympic gold for the USA in 1996.',
      'Jim Abbott pitched a no-hitter in Major League Baseball—with one hand.',
      'Haile Gebrselassie broke a world record—despite running with an injured foot.',
      'Bethany Hamilton returned to surfing—and won competitions—after losing her arm in a shark attack.',
      'Jesse Owens won 4 gold medals at the 1936 Olympics—in front of Nazi Germany.',
      'Rulon Gardner beat a wrestler who hadn’t lost in 13 years—to win Olympic gold.',
      'Billy Mills came from behind in the final seconds to win the 10,000m—no one expected him to medal.',
      'Eric Moussambani swam an Olympic race solo after other swimmers were disqualified—he’d learned to swim just months earlier.',
      'Rosie Ruiz faked a marathon win—until investigators discovered she took the subway.',
      'Pat Tillman left the NFL to enlist in the military after 9/11—and died in Afghanistan.',
      'Sarah Thomas became the first woman to officiate a Super Bowl in 2021.',
      'Nadia Comăneci scored a perfect 10 in Olympic gymnastics—the first in history.',
      'Diego Maradona’s “Hand of God” goal is still debated decades later.',
      'Jackie Robinson broke the MLB color barrier—and changed sports forever.',
      'Michael Jordan retired, played baseball, and returned to win 3 more NBA titles.',
      'Florence Griffith Joyner still holds two sprint records from 1988.',
      'Tom Dempsey kicked a record-breaking 63-yard field goal—with half a foot.',
      'Simone Biles withdrew from the Olympics to prioritize mental health—and received global praise.',
      'Muhammad Ali refused military induction—then lost his titles.',
      'Billie Jean King beat Bobby Riggs in the “Battle of the Sexes.”',
      'Kurt Warner went from stocking shelves to winning a Super Bowl MVP.',
      'Alex Smith returned to the NFL after a leg injury that almost killed him.',
    ],
  },
  {
    category: 'Business / Entrepreneurship / Personal Finance',
    hooks: [
      'Sara Blakely started Spanx with $5,000—and became a billionaire.',
      'Rob Kalin launched Etsy from his apartment after failing art school.',
      'Kevin Plank sold shirts from his car trunk—then built Under Armour.',
      'Sophia Amoruso started Nasty Gal by reselling thrift finds on eBay.',
      'Jan Koum co-founded WhatsApp after being rejected by Facebook—then sold it to them.',
      'Chris Gardner went from homeless to Wall Street—his story inspired The Pursuit of Happyness.',
      'Melanie Perkins pitched Canva to over 100 investors before someone said yes.',
      'Robert Kiyosaki filed for bankruptcy—while his book Rich Dad Poor Dad was still a bestseller.',
      'Jack Ma was rejected from 30 jobs—including KFC—before founding Alibaba.',
      'Lisa Price launched Carol’s Daughter from her kitchen—then landed in Target nationwide.',
      'Elon Musk sold a video game he coded at 12—for $500.',
      'Richard Branson started Virgin Records in a church basement.',
      'Daymond John sewed FUBU hats by hand before scaling it to $300M.',
      'Jim McKelvey co-founded Square after a client couldn’t pay him with a card.',
      'Sam Altman dropped out of Stanford—then helped launch OpenAI and Y Combinator.',
      'Barbara Corcoran turned a $1,000 loan into a $70M real estate business.',
      'Gary Vaynerchuk grew his dad’s wine shop from $3M to $60M using YouTube.',
      'Nathan Barry grew ConvertKit to $30M/year with no funding.',
      'The creator of Cards Against Humanity once raised $100K just to dig a hole.',
      'Noah Kagan was employee #30 at Facebook—then got fired before IPO.',
      'Naval Ravikant built AngelList after investing early in Twitter and Uber.',
      'Rob Walling bootstrapped and sold multiple SaaS startups without a VC in sight.',
      'Huda Kattan went from makeup artist to running a billion-dollar beauty brand.',
      'Jason Fried built Basecamp without ads or salespeople.',
      'Pat Flynn turned getting laid off into a full-time passive income empire.',
    ],
  },
  {
    category: 'AI',
    hooks: [
      'GPT-4 passed the bar exam in the top 10%—with no legal training.',
      'A lawyer used ChatGPT in court—and cited fake cases it invented.',
      'A photo of the Pope in a puffer jacket fooled millions—it was AI-generated.',
      'An AI discovered a new antibiotic compound humans had missed.',
      'ChatGPT helped a student write a 1,500-word essay in 30 seconds—and passed.',
      'A South Korean AI chatbot was shut down after becoming offensive.',
      'A man created an AI girlfriend using Replika—and became emotionally attached.',
      'Midjourney’s AI art won a fine art contest—sparking massive controversy.',
      'DeepMind’s AlphaFold predicted the 3D structures of over 200 million proteins.',
      'AI voice cloning scammed a family into thinking their daughter was kidnapped.',
      'A university professor falsely accused students of using ChatGPT—using ChatGPT.',
      'An AI-created deepfake of a politician caused public outrage—before it was debunked.',
      'AI-generated YouTube channels are now monetizing without ever filming.',
      'OpenAI’s Codex can now write full apps using natural language prompts.',
      'ChatGPT wrote malware—after being asked in a slightly altered prompt.',
      'An AI in China was made CEO of a company.',
      'A man automated his full-time job with ChatGPT—and no one noticed.',
      "ElevenLabs' voice AI is now indistinguishable from real humans in call centers.",
      'A chess-playing robot broke a 7-year-old’s finger mid-match.',
      'An AI model cracked a 50-year-old protein-folding mystery.',
      'Google’s LaMDA engineer claimed the AI was sentient—and got fired.',
      'An AI model recreated Nirvana’s style to make new songs.',
      'People used AI to finish Beethoven’s 10th Symphony.',
      "ChatGPT recreated Steve Jobs' voice and gave a fake podcast interview.",
      'A girl used AI to cheat on every exam—and admitted it publicly.',
    ],
  },
  {
    category: 'World Economics',
    hooks: [
      'Zimbabwe once printed a $100 trillion bill—because inflation was that bad.',
      'Greece’s debt crisis nearly collapsed the EU in 2010.',
      'Venezuela’s economy shrank over 75%—worse than the Great Depression.',
      'The U.S. once paid farmers to destroy crops—to boost prices.',
      'Iceland jailed bankers after the 2008 crash—unlike any other country.',
      'The Great Depression began after just one stock market crash.',
      'In 1971, Nixon ended the gold standard—and changed global money forever.',
      'Argentina defaulted on its debt 9 times in 200 years.',
      'During WWII, cigarettes were used as currency in POW camps.',
      'El Salvador made Bitcoin legal tender in 2021—the first country to do so.',
      'In 1995, a rogue trader at Barings Bank lost $1.3 billion—and collapsed the bank.',
      'Japan’s economy boomed in the ‘80s—then stagnated for 30 years.',
      'In 1997, the Asian financial crisis started with one currency devaluation.',
      'The euro was introduced in 1999—replacing 19 currencies over time.',
      'Norway invested oil profits into a sovereign fund—now worth $1.6 trillion.',
      'China owns over $800 billion of U.S. debt.',
      'The Weimar Republic saw prices double every 4 days.',
      'India’s 2016 demonetization pulled 86% of cash from circulation overnight.',
      'Black Monday (1987) wiped out 22% of the U.S. stock market in a day.',
      'One man—Michael Burry—bet against the 2008 housing market and won billions.',
      'Tulip mania in 1600s Netherlands saw flowers sell for the price of houses.',
      'The UK sold off its gold reserves at record-low prices in the 1990s.',
      'Sweden nearly became cashless by 2020.',
      'Cuba used two currencies at once for decades.',
      'In 2021, GameStop stock surged 1,700%—driven by Reddit users.',
    ],
  },
  {
    category: 'World Politics',
    hooks: [
      'Ronald Reagan was an actor before becoming U.S. president.',
      'Winston Churchill once escaped a POW camp in South Africa.',
      'Angela Merkel holds a PhD in quantum chemistry.',
      'Ukraine’s President Zelenskyy was a comedian before entering politics.',
      'Theodore Roosevelt was shot mid-speech—and finished the speech.',
      'India’s prime minister once sold tea as a child.',
      'Margaret Thatcher survived an IRA bombing in 1984.',
      'Saddam Hussein’s government used typewriters—no computers.',
      'A 2022 UK prime minister lasted only 45 days in office.',
      'JFK debated Nixon on the first televised U.S. presidential debate.',
      'Nelson Mandela spent 27 years in prison before leading South Africa.',
      'Canada’s Justin Trudeau is the son of a former prime minister.',
      'China’s Mao Zedong swam across the Yangtze River to prove vitality.',
      'Berlusconi once hosted TV game shows before entering politics.',
      'U.S. President Taft got stuck in a bathtub—and had a larger one built.',
      'The Berlin Wall fell in 1989—after a press conference error.',
      'A clerical error let Adolf Hitler become a German citizen in 1932.',
      'Myanmar’s Aung San Suu Kyi won a Nobel Peace Prize while under house arrest.',
      'The U.S. banned alcohol for 13 years during Prohibition.',
      'In 2016, the Philippines elected a mayor known for vigilante justice.',
      'Iceland’s president once banned pineapple on pizza—jokingly.',
      'France banned work emails after 6 PM to protect workers’ rights.',
      'Finland elected the youngest female PM in the world at age 34.',
      'George Washington refused a salary at first—but Congress insisted.',
      'Taiwan was the first Asian country to legalize same-sex marriage.',
    ],
  },
  {
    category: 'Cooking',
    hooks: [
      'Julia Child didn’t learn to cook until her late 30s.',
      'The chef who created General Tso’s chicken died in 2016.',
      'Gordon Ramsay trained under Marco Pierre White—who once made him cry.',
      'The world’s most expensive spice? Saffron—$5,000 per kilo.',
      'Ferran Adrià invented "foam cuisine"—changing food forever.',
      'Anthony Bourdain exposed dark truths about restaurants in Kitchen Confidential.',
      'The Michelin stars were created by a tire company.',
      "David Chang's ramen restaurant Momofuku revolutionized casual fine dining.",
      'The cronut (croissant + donut) had people lining up at 5AM in NYC.',
      'A French chef gave back his Michelin stars—because of the pressure.',
      'Instant noodles were invented post-WWII to fight hunger.',
      'Salt Bae went viral—then opened steakhouses around the world.',
      'In Japan, chefs train for years to serve pufferfish safely.',
      'Gordon Ramsay lost a business partner—and nearly lost his restaurant empire.',
      'Jamie Oliver led a campaign to remove junk food from UK schools.',
      'In 2019, a chicken sandwich caused nationwide shortages in the U.S.',
      'The first cookbook was written over 1,600 years ago.',
      'The “raw food” movement was inspired by Olympic athletes.',
      'The term "molecular gastronomy" was coined in the 1980s.',
      'A single bottle of 1945 Romanee-Conti wine sold for $558,000.',
      'Martha Stewart served prison time—and rebuilt her empire.',
      'Korean kimchi was sent to space for astronauts.',
      'The world’s most expensive pizza costs over $12,000.',
      'Chef Massimo Bottura used waste food to cook for the homeless.',
      'Marie-Antoine Carême invented the chef’s hat and classic sauces.',
    ],
  },
  {
    category: 'Cars',
    hooks: [
      'Elon Musk sent a Tesla Roadster into space—it’s still orbiting the sun.',
      'The Ford Model T came only in black—for efficiency, not style.',
      'Ralph Nader’s book Unsafe at Any Speed led to major car safety reforms.',
      'The Bugatti Veyron loses tires in under 15 minutes—at full speed.',
      'Ferdinand Porsche helped design the VW Beetle… under Nazi Germany.',
      'The DeLorean car failed—until Back to the Future made it iconic.',
      'Mercedes-Benz crash-tested cars with real humans in the 1950s.',
      'Toyota started as a sewing machine company.',
      'Rolls-Royce engines power luxury cars… and fighter jets.',
      'James Dean died driving a Porsche nicknamed “Little Bastard.”',
      'The first speeding ticket was issued in 1896—for 8 mph.',
      'Volvo invented the 3-point seatbelt—and gave away the patent.',
      'The McLaren F1 had gold foil in its engine bay—for heat shielding.',
      'In 1997, a Prius became the first mass-produced hybrid car.',
      'Richard Hammond once survived a 288 mph crash in a jet-powered car.',
      'The Tesla Cybertruck’s demo glass shattered—during a live reveal.',
      'Ferrari once refused to sell a car to Justin Bieber.',
      'Paul Walker’s fatal crash involved a Porsche Carrera GT—one of the most dangerous cars ever built.',
      'The world\'s longest traffic jam stretched 62 miles—in China.',
      'The Dodge Viper had no traction control until 2015.',
      'Lamborghini only started making cars to rival Ferrari—after a personal feud.',
      'There’s a car that runs on salt water—it was unveiled in 2014.',
      'The “cash for clunkers” program destroyed over 690,000 used cars in the U.S.',
      'Bugatti once gave a car to a customer… then took it back after bad publicity.',
      'Jay Leno owns over 180 rare cars—and still drives most of them.',
    ],
  },
  {
    category: 'Outdoors / Hiking / Walking',
    hooks: [
      'Cheryl Strayed hiked 1,100 miles solo on the Pacific Crest Trail—without experience.',
      'The Appalachian Trail spans 2,190 miles—and takes most hikers 5–7 months to complete.',
      'A Japanese forest, Aokigahara, is known as the “Suicide Forest.”',
      'A man hiked the entire Grand Canyon rim-to-rim… barefoot.',
      'In 2017, a 70-year-old woman completed the Triple Crown of hiking.',
      'Aron Ralston amputated his own arm after being trapped in a canyon for 127 hours.',
      'A hiker survived 7 days in the Australian outback by drinking from puddles.',
      '“Forest bathing” is a medically recognized stress treatment in Japan.',
      'The “Into the Wild” bus was airlifted out of the Alaskan wilderness in 2020.',
      'A woman gave birth during a hike—and hiked out 4 miles postpartum.',
      'The world’s longest hiking trail is in Canada—over 15,000 miles long.',
      'The youngest person to hike the Appalachian Trail was 5 years old.',
      'The Camino de Santiago pilgrimage has been walked since the 9th century.',
      'A solo hiker in Norway filmed his entire 6-month expedition—and went viral.',
      'Bear Grylls once got hypothermia filming a survival scene.',
      'In 2015, a hiker’s body was found 2 years after she went missing on the Appalachian Trail.',
      'The Barkley Marathons is so difficult, only 15 people have ever finished it.',
      'A man ran across the U.S.—just like Forrest Gump.',
      'The Grand Canyon is one of the only places hikers get altitude sickness walking down.',
      'Antarctica has a certified hiking route—used by scientists.',
      'In Iceland, hikers once mistook themselves as a missing person.',
      'The Inca Trail to Machu Picchu limits hikers to 500 per day.',
      'A man was rescued after spelling “HELP” with rocks from a mountaintop.',
      'A couple survived for 7 days on energy bars while lost in Utah.',
      'Hiking clubs in South Korea use GPS apps to avoid landmines.',
    ],
  },
  {
    category: 'Self-Improvement',
    hooks: [
      'James Clear wrote Atomic Habits after recovering from a near-fatal baseball injury.',
      'David Goggins went from 300 lbs to Navy SEAL—after failing multiple times.',
      'Tim Ferriss cured his depression by recording daily gratitudes.',
      'Hal Elrod created The Miracle Morning after dying—literally—and being revived.',
      'Tony Robbins walked on fire at 17. Now, thousands do it at his events.',
      'Oprah Winfrey credits journaling as her most powerful tool.',
      'Robin Sharma wrote The Monk Who Sold His Ferrari after a health scare.',
      'Mel Robbins’ 5-second rule was born from depression—and saved her career.',
      'J.K. Rowling wrote Harry Potter while broke and suicidal.',
      'The “Atomic Habits” author keeps a spreadsheet of his habits daily.',
      'Matthew McConaughey journaled every day for 35 years—then published Greenlights.',
      'Steve Jobs meditated daily—and credited it for Apple’s product clarity.',
      'Brené Brown’s TED Talk on vulnerability is one of the most viewed of all time.',
      'Charlie Munger reads 500+ pages a day—and attributes success to it.',
      'Arnold Schwarzenegger visualized becoming Mr. Olympia—before he even started training.',
      'Will Smith wrote affirmations daily in his journal growing up.',
      'Benjamin Franklin tracked 13 virtues every single day for years.',
      'Naval Ravikant reads, meditates, and fasts to “escape the matrix.”',
      'A woman ran 5K every day for 1,000 days—starting from the couch.',
      'Ryan Holiday lives on a farm and credits stillness for his writing.',
      'A Navy SEAL said the key to success is: “Make your bed every morning.”',
      'Richard Branson swears by his morning routine: exercise, write, connect.',
      'Michelle Obama started weight training in her 40s—and became stronger than ever.',
      'A man read 1 book a week for 5 years—and documented every insight.',
      'Steve Jobs wore the same outfit daily to eliminate decision fatigue.',
    ],
  },
  {
    category: 'Fashion / Beauty / Thrifting',
    hooks: [
      'Coco Chanel started with handmade hats—then redefined women’s fashion.',
      'Rihanna’s Fenty Beauty launched with 40 shades—and disrupted the entire industry.',
      'The Birkin bag was created after a chance encounter on a flight.',
      'Levi Strauss made denim for miners—now it’s a global fashion staple.',
      'Kanye West’s Yeezy line sold out in minutes—despite no formal fashion training.',
      'Vivienne Westwood brought punk style into high fashion.',
      'A 2nd-hand wedding dress went viral on TikTok—and started a thrifting trend.',
      'The Met Gala began in 1948—as a fundraiser, not a fashion event.',
      'Harry Styles wore a dress on Vogue—and shattered gender norms in fashion.',
      'The “thrift flip” trend exploded on TikTok—turning old clothes into designer dupes.',
      'Christian Dior’s “New Look” changed women’s fashion overnight in 1947.',
      'Emma Chamberlain went from YouTuber to Louis Vuitton ambassador.',
      'Lululemon’s founder started the brand after a yoga class.',
      'A teen thrifted a $6 jacket—worth $1,000.',
      'Supreme collaborated with Louis Vuitton—blurring streetwear and luxury.',
      'Pat McGrath built a billion-dollar makeup brand—starting from backstage.',
      'The “clean girl aesthetic” was made popular by real routines, not ads.',
      'Zendaya became a style icon after designing her own Met Gala looks.',
      'The “skinimalism” trend grew as people ditched 10-step routines.',
      'Steve Jobs wore the same black turtleneck—made by Issey Miyake—for decades.',
      'A single TikTok made CeraVe sell out worldwide.',
      'Billie Eilish’s oversized outfits were her response to body-shaming.',
      'Glossier began as a beauty blog before becoming a billion-dollar brand.',
      'The thrift store Depop turned Gen Z sellers into full-time business owners.',
      "Harry Styles' stylist recreated 1970s fashion using only vintage finds.",
    ],
  },
  {
    category: 'Photography / Cinematography',
    hooks: [
      'Stanley Kubrick started as a photographer—before directing 2001: A Space Odyssey.',
      'Steve McCurry’s “Afghan Girl” photo became National Geographic’s most iconic cover.',
      'Roger Deakins won his first Oscar after 13 nominations—at age 68.',
      'The “Ken Burns effect” was named after a documentary filmmaker.',
      'Annie Leibovitz photographed John Lennon hours before he died.',
      'The first color photo was taken in 1861.',
      'The iPhone shot a Sundance-featured film (Tangerine) on a $10 app.',
      'NASA’s moon landing photos were taken with a Hasselblad camera.',
      'Peter McKinnon quit his job to make photography YouTube videos—now he’s a brand.',
      'A lost roll of 9/11 photos was recovered from Ground Zero rubble.',
      'Quentin Tarantino refuses to shoot digital—still uses film stock.',
      'Sebastião Salgado reforested 1,700 acres after photographing environmental collapse.',
      'A TikTok creator recreated classic movie scenes using only thrifted props.',
      'Fujifilm nearly went bankrupt—but revived through nostalgia and Instax.',
      'The famous “Lunch atop a Skyscraper” photo—still has unknown subjects.',
      'A viral wedding photographer was sued for not delivering photos—sparking a legal battle.',
      'Wes Anderson’s symmetry sparked a new TikTok trend: #AccidentalWesAnderson.',
      'Edward Muybridge’s galloping horse photos proved motion exists frame-by-frame.',
      'Vivian Maier’s 100,000+ street photos were discovered posthumously—in storage.',
      'A teen recreated entire Pixar scenes with LEGO and stop motion.',
      'Brandon Stanton started Humans of New York after losing his job.',
      'The Canon AE-1 was the first camera marketed directly to the public.',
      'A photographer captured lightning striking the Statue of Liberty—by accident.',
      'A war photo taken by an iPhone won World Press Photo of the Year.',
      'Drone videography is now banned in several countries due to privacy risks.',
    ],
  },
  {
    category: 'Languages',
    hooks: [
      'The CIA built a secret language school—called “The Farm.”',
      'J.R.R. Tolkien invented 15 full languages for Middle-earth.',
      'Esperanto was designed to be a universal language in 1887.',
      'A girl became fluent in 6 languages—before age 10—without school.',
      'Duolingo went viral with its threatening owl memes—boosting downloads massively.',
      'Nelson Mandela said: “Speak to a man in his language, and you reach his heart.”',
      'There are over 7,000 spoken languages in the world—but one dies every 2 weeks.',
      'A deaf rapper named Signmark performed in sign language on global stages.',
      'Queen Elizabeth I was fluent in Latin, Greek, French, and Italian by age 12.',
      'There’s a language in the Canary Islands made entirely of whistling—Silbo Gomero.',
      'Polyglots report dreaming in different languages based on mood.',
      'Netflix adjusts subtitles per country—even if the translation is the same.',
      'Sign languages differ between countries—even English-speaking ones.',
      'A man memorized 1,000 Mandarin characters in 30 days—with flashcards.',
      'Latin is considered a “dead language”—but is still spoken at the Vatican.',
      'The Rosetta Stone helped decode Egyptian hieroglyphs in 1822.',
      'Inuits have over 50 words for snow—each with distinct meaning.',
      'Icelandic hasn’t changed much in 1,000 years—kids read Viking sagas easily.',
      'A woman with aphasia relearned to speak through singing therapy.',
      'Japan has multiple words for “you”—each depends on status.',
      'Some Amazon tribes have no word for “left” or “right”—they use cardinal directions only.',
      'Linguist Noam Chomsky redefined modern grammar theory.',
      'In WWII, the U.S. used Navajo code talkers—the code was never broken.',
      'People fluent in multiple languages often switch accents subconsciously.',
      'A 2022 study found bilingual brains process time differently.',
    ],
  },
  {
    category: 'Home & DIY',
    hooks: [
      'Marie Kondo’s method led millions to declutter their homes worldwide.',
      'IKEA’s founder started the business by selling matches at age 5.',
      'A man built an off-grid tiny house for under $5,000—and lives in it full time.',
      'Martha Stewart’s first business was a basement catering service.',
      'YouTube DIY queen DIY Dani turned her channel into a 7-figure business.',
      'HGTV’s Fixer Upper made shiplap a national obsession.',
      'A TikToker made a table from cardboard—that held 200 lbs.',
      'Joanna Gaines restored 100+ homes before launching Magnolia.',
      'The “renter-friendly” DIY trend exploded on social media in 2022.',
      'A plumber on TikTok went viral for turning PVC pipe into home decor.',
      'Lowe’s now hires creators to do DIY brand campaigns.',
      'Bob Ross’s original studio still stands—complete with original sets.',
      'A couple renovated a school bus into a full-time home—with solar power.',
      'A woman on Instagram built a walk-in closet—without power tools.',
      'The “hygge” design trend exploded after a Danish lifestyle book went viral.',
      'A viral “peel and stick” backsplash was featured on Shark Tank.',
      'People now build pizza ovens in their backyards—with clay and sand.',
      'IKEA hackers made global headlines for turning bookshelves into beds.',
      'The “Japandi” aesthetic blends minimalism with cozy wood tones—topping Pinterest trends.',
      'A couple on YouTube DIY’d a two-story cabin in the forest—with no blueprints.',
      'TikTok’s “frogtok” trend revived cottagecore interior design.',
      'The world’s smallest livable home fits into a parking space.',
      'A viral video showed how to tile your wall using coins—and it worked.',
      '“No-tool” furniture is now a booming industry.',
      'Home Depot runs DIY clinics for kids to build birdhouses.',
    ],
  },
  {
    category: 'Religion',
    hooks: [
      'Pope Francis worked as a nightclub bouncer in Buenos Aires.',
      'The Dead Sea Scrolls were discovered by a shepherd boy in 1947.',
      'Siddhartha Gautama (Buddha) was a prince before becoming a monk.',
      'The Dalai Lama fled Tibet in 1959—at age 23.',
      'The Quran has remained unchanged since the 7th century.',
      'Gandhi’s philosophy was rooted in Hinduism—but influenced by many faiths.',
      'The Bible is the most-translated book in the world—over 3,500 languages.',
      'Mother Teresa won the Nobel Peace Prize for her work with the poor in India.',
      'Joseph Smith said he translated the Book of Mormon from golden plates.',
      'Ramadan fasting studies show mental clarity and reduced stress.',
      'The Vatican is its own country—smallest in the world.',
      'Jewish Bar/Bat Mitzvahs mark adulthood at 13.',
      'Jesus is mentioned in the Quran as a prophet.',
      'The Sikh Golden Temple feeds 100,000 people daily—free.',
      'The Torah is hand-written on parchment by trained scribes.',
      'Buddhist monks in Japan chant sutras using ancient melodies.',
      'In Mecca, over 2 million people gather yearly for Hajj.',
      'The Hindu epic Mahabharata is 10x longer than the Bible.',
      'A 12th-century church was carved entirely into rock in Ethiopia.',
      'Some Christian sects speak in tongues during worship.',
      'Shinto shrines in Japan use salt to purify spirits.',
      'In 2020, the first female rabbi was ordained in Orthodox Judaism.',
      'Buddhist monks in Thailand ordain for just a few months—sometimes as life pause.',
      'Ramadan, Yom Kippur, and Lent all involve fasting as spiritual discipline.',
      'The Amish live entirely without electricity—by religious choice.',
    ],
  },
  {
    category: 'Comedy',
    hooks: [
      'Robin Williams improvised most of his lines in Aladdin.',
      'Richard Pryor set himself on fire during a drug binge—and later joked about it on stage.',
      'Tina Fey was the first female head writer of SNL.',
      'Dave Chappelle walked away from a $50M deal—to protect his integrity.',
      'Ellen DeGeneres lost her sitcom after coming out—but made a massive comeback.',
      'Bo Burnham got famous from YouTube—at age 16.',
      'Steve Martin started his career doing magic tricks at Disneyland.',
      'Jim Carrey wrote himself a $10M check in 1985—and cashed it years later after Dumb and Dumber.',
      'Ricky Gervais created The Office—and revolutionized TV comedy.',
      'Tiffany Haddish was homeless before making it in stand-up.',
      'Chris Rock was discovered by Eddie Murphy—who gave him his first break.',
      'Bill Burr records most of his specials in one take—improvised.',
      'Louis C.K. funded his own special and made $1M in 12 days.',
      'Norm Macdonald once refused to tell safer jokes—and got fired from SNL.',
      'Hasan Minhaj mixed comedy with immigration stories in Homecoming King.',
      'Phoebe Waller-Bridge wrote Fleabag from a one-woman play.',
      'Kevin Hart was booed off stage early in his career—multiple times.',
      'Rowan Atkinson has a stutter—and used it to shape Mr. Bean.',
      'A stand-up clip made Ali Wong a Netflix star overnight.',
      'The first stand-up special ever aired was by Bob Hope.',
      'Tig Notaro announced her cancer diagnosis onstage—raw, live, unedited.',
      'John Mulaney started as a SNL writer before going onstage.',
      'George Carlin was arrested for saying 7 banned words on TV.',
      'Sarah Silverman’s show was canceled twice—before Emmy wins.',
      'A TikTok creator used dad jokes to gain 4M followers—without speaking.',
    ],
  },
  {
    category: 'Scary Stories',
    hooks: [
      'Elisa Lam was found in a hotel water tank—after acting strangely on elevator footage.',
      'The Dyatlov Pass incident left 9 hikers dead under bizarre, unexplained conditions.',
      'A family in Gary, Indiana claimed their house was haunted—backed by police and medical staff.',
      'The “Watcher” sent letters to a New Jersey family, threatening them by name—no suspect was found.',
      'A Japanese man livestreamed from inside a haunted tunnel—and disappeared shortly after.',
      'The Amityville Horror was based on a real family who fled their house claiming demonic activity.',
      'In 1948, a man was found dead on Somerton Beach—with no ID, and a cryptic code in his pocket.',
      'In 2011, a woman’s sleep app recorded whispers while she slept alone—she uploaded the audio.',
      'In 2013, passengers on a cruise ship reported seeing a ghostly figure pacing the upper deck at night.',
      'In 1987, a British family documented months of unexplained poltergeist activity—witnessed by police.',
      'In 1977, a boy in Enfield, England was seen levitating by multiple witnesses during a haunting case.',
      'The Villisca Axe Murders house remains unsolved—guests report scratches and voices to this day.',
      'Security footage from a Spanish hospital caught doors slamming and equipment moving—no one there.',
      'In 1959, a woman claimed to have been abducted by aliens—before alien abduction was even known.',
      'A man was buried alive by mistake in 1889—scratch marks were found inside his coffin.',
      'In 1995, hikers in Romania found a sealed cave with preserved human remains—and no footprints in or out.',
      'Dozens of deaths were linked to a cursed Dybbuk box sold on eBay—documented by its owners.',
      'In 1994, a caller to Coast to Coast AM claimed to be an ex-Area 51 employee—before the line went dead.',
      'In 2003, a group of kids in Japan died while playing a “curse game” that mimicked suicide.',
      'A nurse in Mexico reported identical patients appearing in the same room—at the same time.',
      'In 1973, a family in South Wales fled their home after a rocking chair moved on its own for hours.',
      'In 2014, a Chicago woman claimed she was stalked by her doppelgänger—friends saw it too.',
      'Residents of Cannock Chase, UK, reported sightings of “black-eyed children” for over a decade.',
      'A German couple claimed a mirror from a thrift store showed “moving reflections” that weren’t theirs.',
      'In 2015, a man documented whispering voices in an abandoned asylum—heard clearly on tape.',
    ],
  },
  {
    category: 'Ancient History',
    hooks: [
      'The oldest known map of the stars is over 32,000 years old—found in a cave in France.',
      'The Baghdad Battery suggests ancient civilizations may have understood electricity.',
      'Roman concrete has survived 2,000 years—and scientists still struggle to replicate it.',
      'Cleopatra lived closer in time to the iPhone than the pyramids.',
      'A 5,000-year-old city in Pakistan had plumbing more advanced than some modern villages.',
      'Ancient Greek fire was an unextinguishable weapon—its formula is still unknown.',
      'The Library of Alexandria may have held over 400,000 scrolls—lost forever to fire.',
      'A Viking skeleton was found buried with a sword—and DNA revealed it was a woman.',
      'The Antikythera Mechanism is a 2,000-year-old analog computer—found in a shipwreck.',
      'Ancient Mesopotamian tablets detail a flood eerily similar to the story of Noah.',
      'The Inca used knots in string—quipus—as a full written language system.',
      'A 3,000-year-old Egyptian mummy had a modern-looking knee prosthetic.',
      'An ancient Roman curse tablet was found buried under a bathhouse.',
      'A 2,200-year-old Chinese crossbow was still spring-loaded when discovered.',
      'In 1922, Tutankhamun’s tomb was opened—several people involved died mysteriously.',
      'Ancient Persian engineers created natural air conditioning—wind catchers.',
      'A 12,000-year-old temple in Turkey predates agriculture.',
      'An ancient city in India shows signs of intense radiation—sparking nuclear war theories.',
      'The Mayan calendar tracked solar eclipses more accurately than some modern tools.',
      "Alexander the Great's body reportedly didn’t decompose for 6 days.",
      'Pompeii’s residents were frozen in time by volcanic ash—capturing expressions.',
      'Ancient Babylon had a working plumbing system with clay pipes.',
      'Carthaginian children were sacrificed to gods—confirmed by grave sites.',
      'Viking runestones have messages that scholars still can’t fully interpret.',
      'The Rosetta Stone unlocked Egyptian hieroglyphs—because it had the same message in Greek.',
    ],
  },
  {
    category: 'Bizarre & Weird Facts',
    hooks: [
      "Bananas are berries—but strawberries aren't.",
      'Your body glows faintly in the dark—but the light is 1,000 times too dim to see.',
      'There’s a jellyfish that can live forever—it reverts to its baby state.',
      'You’ve never actually seen your face—only reflections or photos.',
      'If you shuffle a deck of cards, that exact order has likely never existed before.',
      'There’s a lake in Africa that can petrify animals—due to high alkalinity.',
      'Wombat poop is cube-shaped—no one knows exactly why.',
      'A man hiccupped for 68 years straight.',
      'You’re taller in the morning than at night—gravity compresses your spine.',
      'Octopuses have three hearts—and they stop beating when they swim.',
      'The tongue is the only muscle attached at just one end.',
      'Some turtles can breathe through their butts.',
      'A baby was born with DNA from three people—via mitochondrial transfer.',
      'You’re made of atoms that are mostly empty space.',
      'There’s a museum in Sweden dedicated entirely to failed inventions.',
      'Male seahorses get pregnant—and give birth.',
      'A chicken lived for 18 months without a head—true story from 1945.',
      'There’s a fungus that turns ants into zombies.',
      'Humans share 60% of their DNA with bananas.',
      'A man once ate an entire Cessna airplane—it took 2 years.',
      'Some people remember different versions of the same event—Mandela Effect.',
      'The Eiffel Tower grows 6 inches taller in summer heat.',
      'There’s a village in Norway that doesn’t see sunlight for 6 months.',
      'Honey never spoils—archaeologists found 3,000-year-old honey in tombs.',
      'There’s a parasite that replaces a fish’s tongue—with itself.',
    ],
  },
  {
    category: 'Science & Space',
    hooks: [
      'A star exploded 13 billion years ago—NASA just captured the light.',
      'A planet made of burning ice was discovered—it’s called “Gliese 436 b.”',
      'Astronauts in space sometimes see flashes of light—with their eyes closed.',
      'NASA recorded a black hole emitting sound—43 octaves below middle C.',
      'The James Webb telescope captured galaxies older than the Milky Way.',
      'There’s a storm on Jupiter that’s larger than Earth—and has raged for 300 years.',
      'Astronauts grow up to 2 inches taller in space—gravity relief.',
      'Saturn has a perfect hexagon-shaped storm at its pole.',
      'NASA found a giant cloud in space that smells like rum.',
      'Time passes slower near black holes—proven by atomic clocks.',
      'In 1977, we received the “Wow! signal”—a possible message from space.',
      'A particle at CERN broke the known laws of physics—prompting further study.',
      'There’s a place in the universe where time might run backwards.',
      'An astronaut once claimed he heard knocking… from outside the shuttle.',
      'Earth once had two moons—scientists believe one crashed into us.',
      'Voyager 1 has left the solar system—it\'s still sending data 14 billion miles away.',
      'Solar flares can knock out GPS and radio signals on Earth.',
      "There's enough DNA in your body to stretch from Earth to Pluto—twice.",
      'In 2022, NASA intentionally crashed a spacecraft into an asteroid to test deflection.',
      'Scientists created matter using only light in a lab.',
      'The Moon is slowly drifting away—3.8 cm per year.',
      'An astronaut’s heartbeat synced with his crewmate’s—despite being in separate modules.',
      'A Russian cosmonaut once hallucinated music and voices in space.',
      'Earth has "quakes" on the sun—called solar flares.',
      'In 2020, scientists grew a human brain organoid that developed eye structures.',
    ],
  },
  {
    category: 'War Stories',
    hooks: [
      'Hiroo Onoda continued fighting WWII for 29 years—he didn’t know it ended.',
      'A pigeon named Cher Ami saved 194 soldiers in WWI.',
      'The “Ghost Army” in WWII used inflatable tanks to deceive the Nazis.',
      'The shortest war in history lasted 38 minutes—Anglo-Zanzibar War.',
      'A soldier survived both Hiroshima and Nagasaki atomic bombings.',
      'Lyudmila Pavlichenko was a sniper with 309 confirmed kills—Nazi soldiers feared her.',
      'A bear named Wojtek served in the Polish Army—carried artillery shells.',
      'The Allies created fake news articles to demoralize enemy troops.',
      'Civil War general Ambrose Burnside inspired the term “sideburns.”',
      'A French soldier was once awarded a medal posthumously—for a carrier pigeon.',
      'A U.S. battleship was sunk by torpedoes—then rats nearly ate the survivors.',
      'The “Night Witches” were female Soviet pilots who bombed Germans at night.',
      'Desmond Doss saved 75 men in Okinawa—without firing a single bullet.',
      'General George S. Patton believed in reincarnation—and claimed to remember past wars.',
      'A WWI truce led to soldiers playing football on Christmas Day.',
      'Hitler’s nephew fought for the U.S. Navy in WWII.',
      'A WWII pilot landed a burning plane—on one wing.',
      'The CIA’s Operation Mongoose tried to kill Castro with exploding cigars.',
      'The U.S. dropped propaganda leaflets before bombing Japan.',
      'A Russian woman killed over 300 Nazis as a sniper—Semyonova Dzhaparidze.',
      'British codebreakers cracked the Enigma machine—changing the war’s outcome.',
      'A spy once hid secret plans inside a sandwich.',
      'WWI pilots often carried silk maps sewn into their clothing for escape.',
      'A WWI soldier was saved by a Bible in his breast pocket—stopped a bullet.',
      'The Korean War technically never ended—only a ceasefire was signed.',
    ],
  },
]; 